-- Create a table for wardrobe items
create table wardrobe (
  id bigint generated by default as identity primary key,
  user_identifier text not null, -- Since there's no real auth yet, we'll use a mocked identifier
  item_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Allow anonymous access for the hackathon project
alter table wardrobe enable row level security;
create policy "Allow anonymous select" on wardrobe for select using (true);
create policy "Allow anonymous insert" on wardrobe for insert with check (true);
create policy "Allow anonymous delete" on wardrobe for delete using (true);


-- Create a table for user feedback
create table feedback (
  id bigint generated by default as identity primary key,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Allow anonymous access for feedback
alter table feedback enable row level security;
create policy "Allow anonymous insert feedback" on feedback for insert with check (true);
create policy "Allow anonymous select feedback" on feedback for select using (true);
